name: "GitHub Activity Metrics"
description: "Generates GitHub activity metrics and an activity plot for any GitHub user"
author: "Your Name"

inputs:
  user_github:
    description: "GitHub username to analyze"
    required: true
  token_github:
    description: "GitHub personal access token for authentication"
    required: true
  since_days:
    description: "Number of days to fetch commit data"
    required: false
    default: 30
  show_plot:
    description: "Display plot in Action logs (optional)"
    required: false
    default: false

outputs:
  plot_path:
    description: "Path to the activity plot image"

runs:
  using: "docker"
  image: "python:3.9"

  steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Install dependencies"
      run: |
        pip install requests pandas matplotlib numpy mplcyberpunk

    - name: "Run Activity Metrics Script"
      env:
        USER_GITHUB: ${{ inputs.user_github }}
        TOKEN: ${{ inputs.token_github }}
        SINCE_DAYS: ${{ inputs.since_days }}
      run: |
        python script.py

    - name: "Set output path"
      id: output
      run: echo "::set-output name=plot_path::./activity_plot.png"
